
title: My Resume
url: 'http://jerihandika.github.io'
baseurl: '/jerihandika.github.io' #change it according to your repository name



# Profile information
yourname: Jeri Handika  ## put your name
title: 'MAHASISWA' <br> 'Sistem Informasi' <br> 'UIN SUSKA RIAU'  ## your title
location: Pekanbaru , Indonesia


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
